# -*- coding: utf-8 -*-
# @FileName: AriaHandsOps.py

"""
====================================================================================================
Aria Hand Tracking Visualization & Analysis Operations (AriaHandsOps.py)
====================================================================================================

Description:
    This module provides a collection of static utility methods for visualizing and analyzing
    processed hand tracking data from Project Aria Machine Perception Services (MPS).
    It operates on pre-processed AriaHandsData / AriaHands structures and covers two major areas:
    (1) real-time per-frame visualization overlaid on camera images, and (2) offline batch
    analysis plots that compare raw vs. optimized kinematic trajectories over the full sequence.

Core Functionalities:
    1.  Skeleton Visualization: Draws 2D hand skeletons on camera frames using Aria's official
        21-keypoint layout, with per-finger color coding and grasp-state visual feedback.
    2.  Pose Axis Rendering: Projects 3D wrist/midpoint pose axes (X/Y/Z) onto camera images
        using OpenCV's projectPoints, with a decorative base disk and laser pointer effect.
    3.  HUD Overlay: Renders an informational heads-up display showing thumb-index pinch
        distance, wrist-midpoint arm length, and grasp state indicators on each frame.
    4.  Panel UI: Draws per-hand info panels (confidence, joint angle bars, velocity gauge)
        at the bottom corners of the visualization frame.
    5.  Analysis Plots: Generates two comprehensive per-hand (left/right) matplotlib figures
        covering 20+ sub-panels: position/velocity/acceleration trajectories, 3D/2D spatial
        paths, pose deviation (Raw vs. Opt), orientation axes, and a statistics text report.

Generated Outputs:
    📊 aria_hands_analysis_r.png  -- Right-hand full kinematic analysis report figure.
    📊 aria_hands_analysis_l.png  -- Left-hand full kinematic analysis report figure.

Technical Specifics:
    - All optimized ("Opt") data refers to trajectories smoothed via Savitzky-Golay / EMA
      filtering applied upstream in the pipeline (AriaHands.py).
    - Raw ("Raw") data is the direct MPS closed-loop world-frame output before smoothing.
    - Color convention in plots: Red = Raw, Green = Optimized.
    - Coordinate Frame: MPS Closed Loop World frame for 3D; image pixel frame for 2D.
====================================================================================================
"""

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import warnings
from typing import Any, Dict, List, Optional, Tuple
from scipy.spatial.transform import Rotation as R
from scipy.ndimage import uniform_filter1d

from projectaria_tools.core import mps

from utils.utils_vis import draw_glass_rect
from preprocess.AriaHandsTypes import AriaHandsData, AriaHands


# ---------------------------------------------------------------------------
# Analysis plot layout & style constants.
# These control the figure size, grid layout, font sizes, line styles, and
# alpha values for the offline report figures generated by
# save_hands_analysis_plots_two().
# ---------------------------------------------------------------------------
ANALYSIS_FIG_DPI = 300
ANALYSIS_GRID_ROWS = 7
ANALYSIS_GRID_COLS = 4
ANALYSIS_FIGSIZE = (34, 26)
ANALYSIS_TITLE_FONTSIZE = 18
ANALYSIS_SUBTITLE_FONTSIZE = 11
ANALYSIS_LINEWIDTH_MAIN = 2.0
ANALYSIS_LINEWIDTH_AUX = 1.2
ANALYSIS_ALPHA_RAW = 0.28
ANALYSIS_ALPHA_OPT = 0.95
ANALYSIS_ALPHA_FILL = 0.18
ANALYSIS_XTICK_NUM = 8


class AriaHandsOps:
    """
    Static utility class for Aria hand tracking visualization and kinematic analysis.

    All methods are @staticmethod — this class acts as a namespace for grouping
    related operations. No instance state is maintained.

    Method Groups:
        Analysis helpers   : _set_frame_time_ticks, _safe_nan_array,
                             _collect_series_single_hand, _interpolate_and_smooth,
                             _compute_pose_deviation, _compute_acc_from_vel_mag
        Analysis plots     : save_hands_analysis_plots_two, print_summary_and_eval
        Frame visualization: _draw_skeleton, _draw_axis, _draw_aria_hand_panel,
                             _draw_advanced_hud, _draw_opt_wrist_thumb_index_only,
                             draw_aria_hands_panel, draw_aria_hands_skeleton
    """

    @staticmethod
    def _set_frame_time_ticks(ax: Any, frames: np.ndarray, dt: float) -> None:
        """
        Set x-axis tick labels on a matplotlib Axes as "frame index + elapsed time (s)".

        Each tick shows two lines: the integer frame number on top and the corresponding
        timestamp (frame_id * dt) in seconds below, providing intuitive temporal context.

        Args:
            ax     (matplotlib.axes.Axes): The subplot axes to modify.
            frames (np.ndarray)          : 1-D array of frame indices, shape (N,).
            dt     (float)               : Time interval per frame in seconds (1 / fps).

        Returns:
            None
        """
        n = len(frames)
        if n <= 1:
            return
        k = max(2, ANALYSIS_XTICK_NUM)
        tick_ids = np.linspace(0, n - 1, k).astype(int)
        tick_ids = np.unique(tick_ids)

        ax.set_xticks(frames[tick_ids])
        labels = []
        for fid in frames[tick_ids]:
            t = fid * dt
            labels.append(f"{int(fid)}\n{t:.2f}s")
        ax.set_xticklabels(labels, fontsize=9)


    @staticmethod
    def _safe_nan_array(vals: Any) -> np.ndarray:
        """
        Safely convert an arbitrary value or sequence to a float numpy array.

        Handles scalar inputs by wrapping them in a 1-element array, ensuring
        downstream array operations (e.g., indexing, nanmean) are always valid.

        Args:
            vals (Any): A scalar, list, or array-like of numeric values.

        Returns:
            np.ndarray: A float64 numpy array. Scalars become shape (1,).
        """
        arr = np.array(vals, dtype=float)
        if arr.ndim == 0:
            arr = np.array([arr], dtype=float)
        return arr


    @staticmethod
    def _collect_series_single_hand(aria_hands: AriaHands, is_right: bool) -> Dict:
        """
        Extract all per-frame time-series data for one hand from an AriaHands sequence,
        returning a flat dictionary of arrays ready for analysis plotting.

        Iterates over every frame, pulling out confidence, grasp state, raw/optimized 3D
        positions, pose matrices, velocities, 2D projections, and orientation axes.
        Missing frames are represented as NaN. A smoothed thumb-index distance curve
        (dist_opt) and 2D midpoint trajectory (mid2d_opt) are also computed here.

        Args:
            aria_hands (AriaHands): Full hand tracking sequence with per-frame AriaHandsData.
            is_right   (bool)     : True to collect the right hand; False for left hand.

        Returns:
            Dict: A dictionary (from locals()) containing the following numpy arrays:
                - frames          (N,)    : Frame index array [0..N-1].
                - conf            (N,)    : Tracking confidence per frame [0, 1].
                - grasp           (N,)    : Binary grasp state (0=open, 1=closed).
                - dist_raw        (N,)    : Raw thumb-index 3D distance in meters.
                - dist_opt        (N,)    : Smoothed thumb-index distance in meters.
                - mid_raw_xyz     (N, 3)  : Raw midpoint world position (m).
                - mid_opt_xyz     (N, 3)  : Optimized midpoint world position (m).
                - wrist_raw_xyz   (N, 3)  : Raw wrist world position (m).
                - wrist_opt_xyz   (N, 3)  : Optimized wrist world position (m).
                - wrist_pose_raw/opt  (List[4x4 or None]): Per-frame wrist pose matrices.
                - mid_pose_raw/opt    (List[4x4 or None]): Per-frame midpoint pose matrices.
                - wrist/mid_lin/ang_raw/opt (N,): Velocity magnitudes (m/s, rad/s).
                - d_mid2w_raw/opt (N,)    : Midpoint-to-wrist distance in meters.
                - mid2d_raw       (N, 2)  : Raw 2D midpoint in image pixels.
                - mid2d_opt       (N, 2)  : Smoothed 2D midpoint in image pixels.
                - mid_ax_raw/opt  (N, 3, 3): Orientation axis columns in world frame.
        """
        hand_attr = "hand_r" if is_right else "hand_l"
        n = len(aria_hands)
        frames = np.arange(n)
        conf, grasp = np.zeros(n), np.zeros(n)

        # Position and pose containers (NaN = missing frame)
        dist_raw = np.full(n, np.nan)
        mid_raw_xyz, mid_opt_xyz = np.full((n, 3), np.nan), np.full((n, 3), np.nan)
        wrist_raw_xyz, wrist_opt_xyz = np.full((n, 3), np.nan), np.full((n, 3), np.nan)
        wrist_pose_raw, wrist_pose_opt = [None] * n, [None] * n
        mid_pose_raw, mid_pose_opt = [None] * n, [None] * n
        mid2d_raw, mid2d_opt = np.full((n, 2), np.nan), np.full((n, 2), np.nan)

        # Velocity containers (NaN = missing frame)
        wrist_lin_raw, wrist_lin_opt = np.full(n, np.nan), np.full(n, np.nan)
        wrist_ang_raw, wrist_ang_opt = np.full(n, np.nan), np.full(n, np.nan)
        mid_lin_raw, mid_lin_opt = np.full(n, np.nan), np.full(n, np.nan)
        mid_ang_raw, mid_ang_opt = np.full(n, np.nan), np.full(n, np.nan)
        d_mid2w_raw, d_mid2w_opt = np.full(n, np.nan), np.full(n, np.nan)
        mid_ax_raw, mid_ax_opt = np.full((n, 3, 3), np.nan), np.full((n, 3, 3), np.nan)

        for i, frame_data in enumerate(aria_hands.hands):
            h = getattr(frame_data, hand_attr)
            if h is None: continue

            conf[i] = float(h.confidence) if h.confidence is not None else 0.0
            grasp[i] = int(h.grasp_state)

            if h.hand_keypoints_3d is not None:
                dist_raw[i] = np.linalg.norm(h.hand_keypoints_3d[0] - h.hand_keypoints_3d[1])

            if h.midpoint_translation_raw_world is not None: mid_raw_xyz[i, :] = h.midpoint_translation_raw_world
            if h.midpoint_translation_opt_world is not None: mid_opt_xyz[i, :] = h.midpoint_translation_opt_world
            if h.wrist_pose_raw_world is not None:
                wrist_raw_xyz[i, :] = h.wrist_pose_raw_world[:3, 3]
                wrist_pose_raw[i] = h.wrist_pose_raw_world
            if h.wrist_pose_opt_world is not None:
                wrist_opt_xyz[i, :] = h.wrist_pose_opt_world[:3, 3]
                wrist_pose_opt[i] = h.wrist_pose_opt_world

            mid_pose_raw[i] = h.midpoint_pose_raw_world
            mid_pose_opt[i] = h.midpoint_pose_opt_world

            if h.midpoint_pose_raw_world is not None and h.wrist_pose_raw_world is not None:
                d_mid2w_raw[i] = np.linalg.norm(h.midpoint_pose_raw_world[:3, 3] - h.wrist_pose_raw_world[:3, 3])
            if h.midpoint_pose_opt_world is not None and h.wrist_pose_opt_world is not None:
                d_mid2w_opt[i] = np.linalg.norm(h.midpoint_pose_opt_world[:3, 3] - h.wrist_pose_opt_world[:3, 3])

            # Velocity magnitude extraction (None → NaN to preserve array alignment)
            wrist_lin_raw[i] = np.linalg.norm(h.wrist_lin_vel_raw_world) if h.wrist_lin_vel_raw_world is not None else np.nan
            wrist_lin_opt[i] = np.linalg.norm(h.wrist_lin_vel_opt_world) if h.wrist_lin_vel_opt_world is not None else np.nan
            wrist_ang_raw[i] = np.linalg.norm(h.wrist_ang_vel_raw_world) if h.wrist_ang_vel_raw_world is not None else np.nan
            wrist_ang_opt[i] = np.linalg.norm(h.wrist_ang_vel_opt_world) if h.wrist_ang_vel_opt_world is not None else np.nan
            mid_lin_raw[i] = np.linalg.norm(h.midpoint_lin_vel_raw_world) if h.midpoint_lin_vel_raw_world is not None else np.nan
            mid_lin_opt[i] = np.linalg.norm(h.midpoint_lin_vel_opt_world) if h.midpoint_lin_vel_opt_world is not None else np.nan
            mid_ang_raw[i] = np.linalg.norm(h.midpoint_ang_vel_raw_world) if h.midpoint_ang_vel_raw_world is not None else np.nan
            mid_ang_opt[i] = np.linalg.norm(h.midpoint_ang_vel_opt_world) if h.midpoint_ang_vel_opt_world is not None else np.nan

            # 2D midpoint: average of thumb tip (index 0) and index tip (index 1) keypoints
            if h.hand_keypoints_2d is not None and len(h.hand_keypoints_2d) >= 2:
                if not (np.allclose(h.hand_keypoints_2d[0], 0) or np.allclose(h.hand_keypoints_2d[1], 0)):
                    mid2d_raw[i, :] = (h.hand_keypoints_2d[0] + h.hand_keypoints_2d[1]) / 2.0

            # Extract orientation axis columns (x, y, z) from the midpoint rotation matrix
            for pose_obj, ax_container in [(mid_pose_raw[i], mid_ax_raw), (mid_pose_opt[i], mid_ax_opt)]:
                if pose_obj is not None:
                    R_mat = pose_obj[:3, :3]
                    for j in range(3): ax_container[i, j, :] = R_mat[:, j]

        # Post-process: interpolate NaN gaps and apply box smoothing for cleaner plot curves
        dist_opt = AriaHandsOps._interpolate_and_smooth(dist_raw)
        mid2d_opt = np.stack([AriaHandsOps._interpolate_and_smooth(mid2d_raw[:, d]) for d in range(2)], axis=1)

        return locals()


    @staticmethod
    def _interpolate_and_smooth(v: np.ndarray, size: int = 5) -> np.ndarray:
        """
        Fill NaN gaps via linear interpolation, then apply a uniform (box) filter for smoothing.

        Used to produce visually clean curves in analysis plots where missing detections
        (NaN frames) would otherwise create discontinuities.

        Args:
            v    (np.ndarray): 1-D input array potentially containing NaN values, shape (N,).
            size (int)       : Kernel size for uniform_filter1d (box smoothing window).
                               Default is 5.

        Returns:
            np.ndarray: Smoothed 1-D float array of the same shape (N,).
                        Returned unchanged if fewer than 2 valid (non-NaN) samples exist.
        """
        v = v.copy()
        nm = ~np.isnan(v)
        if np.sum(nm) >= 2:
            v[~nm] = np.interp(np.flatnonzero(~nm), np.flatnonzero(nm), v[nm])
            return uniform_filter1d(v, size=size)
        return v


    @staticmethod
    def _compute_pose_deviation(
        raw_list: List[Optional[np.ndarray]],
        opt_list: List[Optional[np.ndarray]]
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Compute per-frame position error (m) and rotation error (degrees) between
        raw and optimized pose matrices.

        For each valid frame pair:
          - Position error = Euclidean distance between translation vectors (||t_raw - t_opt||).
          - Rotation error = rotation angle (deg) of the relative rotation R_raw.T @ R_opt.

        Args:
            raw_list (List[Optional[np.ndarray]]): N-length list of raw 4×4 pose matrices
                                                   (or None for missing frames).
            opt_list (List[Optional[np.ndarray]]): N-length list of optimized 4×4 pose matrices
                                                   (or None for missing frames).

        Returns:
            Tuple[np.ndarray, np.ndarray]:
                - pos_err (np.ndarray, shape N): Per-frame position deviation in meters.
                - rot_err (np.ndarray, shape N): Per-frame rotation deviation in degrees.
                  Both arrays contain NaN for frames where either pose is missing.
        """
        N = len(raw_list)
        pos_err = np.full(N, np.nan)
        rot_err = np.full(N, np.nan)

        for i in range(N):
            if raw_list[i] is None or opt_list[i] is None:
                continue
            pr = raw_list[i][:3, 3]
            po = opt_list[i][:3, 3]
            pos_err[i] = np.linalg.norm(pr - po)

            rr = raw_list[i][:3, :3]
            ro = opt_list[i][:3, :3]
            r_rel = rr.T @ ro
            ang = np.linalg.norm(R.from_matrix(r_rel).as_rotvec())
            rot_err[i] = np.degrees(ang)

        return pos_err, rot_err


    @staticmethod
    def _compute_acc_from_vel_mag(vel_mag: np.ndarray, dt: float) -> np.ndarray:
        """
        Estimate scalar acceleration magnitude via first-order finite difference of velocity.

        For each consecutive valid pair: acc[i] = (vel_mag[i] - vel_mag[i-1]) / dt.
        Used to derive acceleration time series from velocity arrays for analysis plots.

        Args:
            vel_mag (np.ndarray): 1-D velocity magnitude array (m/s or rad/s), shape (N,).
                                  May contain NaN for frames with missing data.
            dt      (float)     : Time step between frames in seconds (1 / fps).

        Returns:
            np.ndarray: 1-D acceleration magnitude array, shape (N,), with NaN where
                        either the current or previous velocity sample is missing.
        """
        v = vel_mag.copy()
        acc = np.full_like(v, np.nan)
        for i in range(1, len(v)):
            if np.isnan(v[i]) or np.isnan(v[i-1]):
                continue
            acc[i] = (v[i] - v[i-1]) / dt
        return acc


    @staticmethod
    def save_hands_analysis_plots_two(
        aria_hands: AriaHands,
        save_dir: str,
        dt: float,
        cfg: Any
    ) -> None:
        """
        Generate and save two comprehensive kinematic analysis figures (right & left hand).

        Each figure is a 7×4 subplot grid covering:
          Row 0: Confidence | Grasp + Thumb-Index Dist | Midpoint X | Midpoint Y
          Row 1: Midpoint Z | Mid Pos Deviation | Mid Rot Deviation | Mid Acc Deviation
          Row 2: Mid 3D Trajectory | Mid 2D Trajectory | Wrist X | Wrist Y
          Row 3: Wrist Z | Wrist Pos Deviation | Wrist Rot Deviation | Wrist Acc Deviation
          Row 4: Wrist 3D Trajectory | Wrist 2D Proxy | Mid↔Wrist Dist | Wrist |v|
          Row 5: Wrist |ω| | Midpoint |v| | Midpoint |ω| | (empty)
          Row 6: Midpoint X-axis | Midpoint Y-axis | Midpoint Z-axis | Text Report

        Each subplot overlays raw (faded) vs. optimized (solid) trajectories for comparison.

        Args:
            aria_hands (AriaHands): Full sequence hand tracking data.
            save_dir   (str)      : Output directory. Created if it does not exist.
            dt         (float)    : Per-frame time step in seconds (1 / fps).
            cfg        (Any)      : Config object with attributes:
                                      cfg.grasp_threshold (float): Pinch distance threshold (m).
                                      cfg.OPT_V_LIMIT     (float): Linear velocity limit (m/s).
                                      cfg.opt_w_limit     (float): Angular velocity limit (rad/s).

        Returns:
            None. Saves files:
                {save_dir}/aria_hands_analysis_r.png
                {save_dir}/aria_hands_analysis_l.png
        """
        os.makedirs(save_dir, exist_ok=True)
        warnings.filterwarnings("ignore", category=UserWarning, module="matplotlib")

        def _safe_legend(ax: Any, fontsize: int = 8, ncol: int = 1) -> None:
            """Draw legend only when labeled artists exist, to suppress matplotlib warnings."""
            handles, labels = ax.get_legend_handles_labels()
            if handles: ax.legend(loc="upper right", fontsize=fontsize, ncol=ncol)

        def _plot_axis_vec(ax: Any, v_raw: np.ndarray, v_opt: np.ndarray, title: str) -> None:
            """
            Plot the X/Y/Z world-frame components of a single orientation axis over time.

            Args:
                ax    (Axes)      : Target subplot axes.
                v_raw (np.ndarray): Raw axis component vectors, shape (N, 3).
                v_opt (np.ndarray): Optimized axis component vectors, shape (N, 3).
                title (str)       : Subplot title string.
            """
            ax.grid(True, alpha=0.35)

            labels = ["Xcomp", "Ycomp", "Zcomp"]
            for j in range(3):
                ax.plot(frames, v_raw[:, j], alpha=ANALYSIS_ALPHA_RAW, linewidth=ANALYSIS_LINEWIDTH_AUX,
                        label=f"Raw {labels[j]}")
                ax.plot(frames, v_opt[:, j], alpha=ANALYSIS_ALPHA_OPT, linewidth=ANALYSIS_LINEWIDTH_MAIN,
                        label=f"Opt {labels[j]}")

            ax.set_title(title, fontsize=ANALYSIS_SUBTITLE_FONTSIZE, fontweight='bold')
            ax.set_ylabel("axis component (unit)")
            ax.set_xlabel("Frame\nTime (s)")
            ax.set_ylim(-1.05, 1.05)
            AriaHandsOps._set_frame_time_ticks(ax, frames, dt)
            ax.legend(loc="upper right", fontsize=8, ncol=2)

        def _plot_ts(ax: Any, y_raw: Optional[np.ndarray] = None, y_opt: Optional[np.ndarray] = None,
                        label_raw: str = "Raw", label_opt: str = "Optimized",
                        ylabel: str = "", title: str = "",
                        show_limit: Optional[float] = None, limit_label: str = "Limit") -> None:
            """
            Generic time-series subplot: plots raw (faded) and optimized (solid) curves
            with an optional dashed horizontal limit line.

            Args:
                ax          (Axes)           : Target subplot axes.
                y_raw       (np.ndarray|None): Raw values, shape (N,). Skipped if None.
                y_opt       (np.ndarray|None): Optimized values, shape (N,). Skipped if None.
                label_raw   (str)            : Legend label for the raw curve.
                label_opt   (str)            : Legend label for the optimized curve.
                ylabel      (str)            : Y-axis label string.
                title       (str)            : Subplot title string.
                show_limit  (float|None)     : If given, draws a dashed horizontal limit line.
                limit_label (str)            : Legend label for the limit line.
            """
            ax.grid(True, alpha=0.35)
            if y_raw is not None:
                ax.plot(frames, y_raw, color=C_RAW, alpha=ANALYSIS_ALPHA_RAW, linewidth=ANALYSIS_LINEWIDTH_AUX, label=label_raw)
            if y_opt is not None:
                ax.plot(frames, y_opt, color=C_OPT, alpha=ANALYSIS_ALPHA_OPT, linewidth=ANALYSIS_LINEWIDTH_MAIN, label=label_opt)
            if show_limit is not None:
                ax.axhline(show_limit, linestyle="--", linewidth=1.2, color="#444444", alpha=0.9, label=limit_label)
            ax.set_title(title, fontsize=ANALYSIS_SUBTITLE_FONTSIZE, fontweight='bold')
            ax.set_ylabel(ylabel)
            ax.set_xlabel("Frame\nTime (s)")
            AriaHandsOps._set_frame_time_ticks(ax, frames, dt)
            ax.legend(loc="upper right", fontsize=9)

        for is_right in [True, False]:
            side_name = "r" if is_right else "l"
            save_path = os.path.join(save_dir, f"aria_hands_analysis_{side_name}.png")

            data = AriaHandsOps._collect_series_single_hand(aria_hands, is_right=is_right)

            frames = data["frames"]
            title_side = "RIGHT HAND" if is_right else "LEFT HAND"

            plt.style.use('seaborn-v0_8-whitegrid')
            fig = plt.figure(figsize=ANALYSIS_FIGSIZE)
            gs = fig.add_gridspec(ANALYSIS_GRID_ROWS, ANALYSIS_GRID_COLS, hspace=0.35, wspace=0.22)

            # Unified color scheme (professional and high contrast)
            C_CONF = "#2E86C1"
            C_GRASP = "#E74C3C"
            C_RAW = "#E74C3C"
            C_OPT = "#2ECC71"
            C_AUX = "#F1C40F"
            C_DEV = "#8E44AD"
            C_ROT = "#8B4513"

            fig.suptitle(
                f"ARIA HAND ADVANCED ANALYSIS REPORT - {title_side}",
                fontsize=ANALYSIS_TITLE_FONTSIZE,
                fontweight='bold'
            )

            # -------------------------
            # 1) Confidence
            # -------------------------
            ax = fig.add_subplot(gs[0, 0])
            ax.grid(True, alpha=0.35)
            ax.plot(frames, data["conf"], color=C_CONF, linewidth=ANALYSIS_LINEWIDTH_MAIN, alpha=0.95, label="Confidence")
            ax.set_title("Hand Tracking Confidence over Time", fontsize=ANALYSIS_SUBTITLE_FONTSIZE, fontweight='bold')
            ax.set_ylim(0, 1.05)
            ax.set_ylabel("Confidence")
            ax.set_xlabel("Frame\nTime (s)")
            AriaHandsOps._set_frame_time_ticks(ax, frames, dt)
            ax.legend(loc="upper right", fontsize=9)

            # -------------------------
            # 2) Grasp action + thumb-index distance (raw/opt) + threshold
            # -------------------------
            ax = fig.add_subplot(gs[0, 1])
            ax.grid(True, alpha=0.35)

            # Grasp state (0/1) as a filled step area
            ax.fill_between(frames, data["grasp"], color=C_GRASP, alpha=0.18, step="pre", label="Grasp State (Closed=1)")

            # Overlay thumb-index distance on a secondary y-axis
            ax2 = ax.twinx()
            ax2.plot(frames, data["dist_raw"], color=C_RAW, alpha=ANALYSIS_ALPHA_RAW, linewidth=ANALYSIS_LINEWIDTH_AUX, label="Thumb-Index Dist (Raw)")
            ax2.plot(frames, data["dist_opt"], color=C_OPT, alpha=ANALYSIS_ALPHA_OPT, linewidth=ANALYSIS_LINEWIDTH_MAIN, label="Thumb-Index Dist (Opt)")
            ax2.axhline(cfg.grasp_threshold, linestyle="--", linewidth=1.2, color="#444444", alpha=0.9, label="cfg.grasp_threshold")

            ax.set_title("Grasp Action + Thumb-Index Distance (Raw/Opt)", fontsize=ANALYSIS_SUBTITLE_FONTSIZE, fontweight='bold')
            ax.set_ylabel("Grasp State")
            ax.set_yticks([0, 1])
            ax.set_xlabel("Frame\nTime (s)")
            AriaHandsOps._set_frame_time_ticks(ax, frames, dt)

            # Merge legends from both axes into the secondary axis
            lines1, labels1 = ax.get_legend_handles_labels()
            lines2, labels2 = ax2.get_legend_handles_labels()
            ax2.legend(lines1 + lines2, labels1 + labels2, loc="upper right", fontsize=8)
            ax2.set_ylabel("Distance (m)")

            # -------------------------
            # 3/4/5) Midpoint X/Y/Z (raw/opt)
            # -------------------------
            ax = fig.add_subplot(gs[0, 2])
            _plot_ts(ax, data["mid_raw_xyz"][:, 0], data["mid_opt_xyz"][:, 0],
                     ylabel="m", title="Midpoint X in World (Raw/Opt)",
                     label_raw="Mid X Raw", label_opt="Mid X Opt")

            ax = fig.add_subplot(gs[0, 3])
            _plot_ts(ax, data["mid_raw_xyz"][:, 1], data["mid_opt_xyz"][:, 1],
                     ylabel="m", title="Midpoint Y in World (Raw/Opt)",
                     label_raw="Mid Y Raw", label_opt="Mid Y Opt")

            ax = fig.add_subplot(gs[1, 0])
            _plot_ts(ax, data["mid_raw_xyz"][:, 2], data["mid_opt_xyz"][:, 2],
                     ylabel="m", title="Midpoint Z in World (Raw/Opt)",
                     label_raw="Mid Z Raw", label_opt="Mid Z Opt")

            # -------------------------
            # 6/7) Midpoint Position/Rotation deviation (opt vs raw)
            # -------------------------
            mid_pos_err, mid_rot_err = AriaHandsOps._compute_pose_deviation(data["mid_pose_raw"], data["mid_pose_opt"])

            ax = fig.add_subplot(gs[1, 1])
            ax.grid(True, alpha=0.35)
            ax.fill_between(frames, mid_pos_err, color=C_DEV, alpha=ANALYSIS_ALPHA_FILL)
            ax.plot(frames, mid_pos_err, color=C_DEV, linewidth=ANALYSIS_LINEWIDTH_MAIN, label="Pos Dev (m)")
            ax.set_title("Midpoint Position Deviation (Opt vs Raw)", fontsize=ANALYSIS_SUBTITLE_FONTSIZE, fontweight='bold')
            ax.set_ylabel("m")
            ax.set_xlabel("Frame\nTime (s)")
            AriaHandsOps._set_frame_time_ticks(ax, frames, dt)
            ax.legend(loc="upper right", fontsize=9)

            ax = fig.add_subplot(gs[1, 2])
            ax.grid(True, alpha=0.35)
            ax.fill_between(frames, mid_rot_err, color=C_ROT, alpha=ANALYSIS_ALPHA_FILL)
            ax.plot(frames, mid_rot_err, color=C_ROT, linewidth=ANALYSIS_LINEWIDTH_MAIN, label="Rot Dev (deg)")
            ax.set_title("Midpoint Rotation Deviation (Opt vs Raw)", fontsize=ANALYSIS_SUBTITLE_FONTSIZE, fontweight='bold')
            ax.set_ylabel("deg")
            ax.set_xlabel("Frame\nTime (s)")
            AriaHandsOps._set_frame_time_ticks(ax, frames, dt)
            ax.legend(loc="upper right", fontsize=9)

            # -------------------------
            # 8) Midpoint Acceleration deviation (raw vs opt, from lin vel mag)
            # -------------------------
            mid_acc_raw = AriaHandsOps._compute_acc_from_vel_mag(data["mid_lin_raw"], dt)
            mid_acc_opt = AriaHandsOps._compute_acc_from_vel_mag(data["mid_lin_opt"], dt)
            mid_acc_dev = np.abs(mid_acc_opt - mid_acc_raw)

            ax = fig.add_subplot(gs[1, 3])
            ax.grid(True, alpha=0.35)
            ax.fill_between(frames, mid_acc_dev, color="#34495E", alpha=ANALYSIS_ALPHA_FILL)
            ax.plot(frames, mid_acc_dev, color="#34495E", linewidth=ANALYSIS_LINEWIDTH_MAIN, label="|Acc Opt - Acc Raw|")
            ax.set_title("Midpoint Acceleration Deviation (Opt vs Raw)", fontsize=ANALYSIS_SUBTITLE_FONTSIZE, fontweight='bold')
            ax.set_ylabel("m/s²")
            ax.set_xlabel("Frame\nTime (s)")
            AriaHandsOps._set_frame_time_ticks(ax, frames, dt)
            ax.legend(loc="upper right", fontsize=9)

            # -------------------------
            # 9) Midpoint 3D trajectory (raw/opt)
            # -------------------------
            ax = fig.add_subplot(gs[2, 0], projection='3d')
            ax.grid(True, alpha=0.3)
            mr = data["mid_raw_xyz"]
            mo = data["mid_opt_xyz"]
            if np.any(~np.isnan(mr[:, 0])):
                ax.plot(mr[:, 0], mr[:, 1], mr[:, 2], color=C_RAW, alpha=0.35, linewidth=1.2, label="Mid Raw")
            if np.any(~np.isnan(mo[:, 0])):
                ax.plot(mo[:, 0], mo[:, 1], mo[:, 2], color=C_OPT, alpha=0.95, linewidth=2.2, label="Mid Opt")
            ax.set_title("Midpoint 3D Trajectory (World)", fontsize=ANALYSIS_SUBTITLE_FONTSIZE, fontweight='bold')
            ax.set_xlabel("X (m)")
            ax.set_ylabel("Y (m)")
            ax.set_zlabel("Z (m)")
            ax.legend(loc="upper right", fontsize=8)

            # -------------------------
            # 10) Midpoint 2D trajectory (raw/opt)
            # -------------------------
            ax = fig.add_subplot(gs[2, 1])
            ax.grid(True, alpha=0.35)
            m2r = data["mid2d_raw"]
            m2o = data["mid2d_opt"]
            if np.any(~np.isnan(m2r[:, 0])):
                ax.plot(m2r[:, 0], m2r[:, 1], color=C_RAW, alpha=0.35, linewidth=1.2, label="Mid 2D Raw")
            if np.any(~np.isnan(m2o[:, 0])):
                ax.plot(m2o[:, 0], m2o[:, 1], color=C_OPT, alpha=0.95, linewidth=2.0, label="Mid 2D Opt")
            ax.set_title("Midpoint 2D Trajectory (Image)", fontsize=ANALYSIS_SUBTITLE_FONTSIZE, fontweight='bold')
            ax.set_xlabel("u (px)")
            ax.set_ylabel("v (px)")
            ax.legend(loc="upper right", fontsize=9)

            # -------------------------
            # 11/12/13) Wrist X/Y/Z (raw/opt)
            # -------------------------
            ax = fig.add_subplot(gs[2, 2])
            _plot_ts(ax, data["wrist_raw_xyz"][:, 0], data["wrist_opt_xyz"][:, 0],
                     ylabel="m", title="Wrist X in World (Raw/Opt)",
                     label_raw="Wrist X Raw", label_opt="Wrist X Opt")

            ax = fig.add_subplot(gs[2, 3])
            _plot_ts(ax, data["wrist_raw_xyz"][:, 1], data["wrist_opt_xyz"][:, 1],
                     ylabel="m", title="Wrist Y in World (Raw/Opt)",
                     label_raw="Wrist Y Raw", label_opt="Wrist Y Opt")

            ax = fig.add_subplot(gs[3, 0])
            _plot_ts(ax, data["wrist_raw_xyz"][:, 2], data["wrist_opt_xyz"][:, 2],
                     ylabel="m", title="Wrist Z in World (Raw/Opt)",
                     label_raw="Wrist Z Raw", label_opt="Wrist Z Opt")

            # -------------------------
            # 14/15) Wrist Position/Rotation deviation
            # -------------------------
            wrist_pos_err, wrist_rot_err = AriaHandsOps._compute_pose_deviation(data["wrist_pose_raw"], data["wrist_pose_opt"])

            ax = fig.add_subplot(gs[3, 1])
            ax.grid(True, alpha=0.35)
            ax.fill_between(frames, wrist_pos_err, color=C_DEV, alpha=ANALYSIS_ALPHA_FILL)
            ax.plot(frames, wrist_pos_err, color=C_DEV, linewidth=ANALYSIS_LINEWIDTH_MAIN, label="Pos Dev (m)")
            ax.set_title("Wrist Position Deviation (Opt vs Raw)", fontsize=ANALYSIS_SUBTITLE_FONTSIZE, fontweight='bold')
            ax.set_ylabel("m")
            ax.set_xlabel("Frame\nTime (s)")
            AriaHandsOps._set_frame_time_ticks(ax, frames, dt)
            ax.legend(loc="upper right", fontsize=9)

            ax = fig.add_subplot(gs[3, 2])
            ax.grid(True, alpha=0.35)
            ax.fill_between(frames, wrist_rot_err, color=C_ROT, alpha=ANALYSIS_ALPHA_FILL)
            ax.plot(frames, wrist_rot_err, color=C_ROT, linewidth=ANALYSIS_LINEWIDTH_MAIN, label="Rot Dev (deg)")
            ax.set_title("Wrist Rotation Deviation (Opt vs Raw)", fontsize=ANALYSIS_SUBTITLE_FONTSIZE, fontweight='bold')
            ax.set_ylabel("deg")
            ax.set_xlabel("Frame\nTime (s)")
            AriaHandsOps._set_frame_time_ticks(ax, frames, dt)
            ax.legend(loc="upper right", fontsize=9)

            # -------------------------
            # 16) Wrist Acceleration deviation (raw vs opt, from lin vel mag)
            # -------------------------
            wrist_acc_raw = AriaHandsOps._compute_acc_from_vel_mag(data["wrist_lin_raw"], dt)
            wrist_acc_opt = AriaHandsOps._compute_acc_from_vel_mag(data["wrist_lin_opt"], dt)
            wrist_acc_dev = np.abs(wrist_acc_opt - wrist_acc_raw)

            ax = fig.add_subplot(gs[3, 3])
            ax.grid(True, alpha=0.35)
            ax.fill_between(frames, wrist_acc_dev, color="#34495E", alpha=ANALYSIS_ALPHA_FILL)
            ax.plot(frames, wrist_acc_dev, color="#34495E", linewidth=ANALYSIS_LINEWIDTH_MAIN, label="|Acc Opt - Acc Raw|")
            ax.set_title("Wrist Acceleration Deviation (Opt vs Raw)", fontsize=ANALYSIS_SUBTITLE_FONTSIZE, fontweight='bold')
            ax.set_ylabel("m/s²")
            ax.set_xlabel("Frame\nTime (s)")
            AriaHandsOps._set_frame_time_ticks(ax, frames, dt)
            ax.legend(loc="upper right", fontsize=9)

            # -------------------------
            # 17) Wrist 3D trajectory (raw/opt)
            # -------------------------
            ax = fig.add_subplot(gs[4, 0], projection='3d')
            ax.grid(True, alpha=0.3)
            wr = data["wrist_raw_xyz"]
            wo = data["wrist_opt_xyz"]
            if np.any(~np.isnan(wr[:, 0])):
                ax.plot(wr[:, 0], wr[:, 1], wr[:, 2], color=C_RAW, alpha=0.35, linewidth=1.2, label="Wrist Raw")
            if np.any(~np.isnan(wo[:, 0])):
                ax.plot(wo[:, 0], wo[:, 1], wo[:, 2], color=C_OPT, alpha=0.95, linewidth=2.2, label="Wrist Opt")
            ax.set_title("Wrist 3D Trajectory (World)", fontsize=ANALYSIS_SUBTITLE_FONTSIZE, fontweight='bold')
            ax.set_xlabel("X (m)")
            ax.set_ylabel("Y (m)")
            ax.set_zlabel("Z (m)")
            ax.legend(loc="upper right", fontsize=8)

            # -------------------------
            # 18) Wrist 2D trajectory proxy
            # Note: wrist 3D cannot be directly projected without camera params here;
            #       the thumb-index midpoint 2D trajectory is used as a structural proxy.
            # -------------------------
            ax = fig.add_subplot(gs[4, 1])
            ax.grid(True, alpha=0.35)
            if np.any(~np.isnan(m2r[:, 0])):
                ax.plot(m2r[:, 0], m2r[:, 1], color=C_RAW, alpha=0.35, linewidth=1.2, label="2D Raw (Mid)")
            if np.any(~np.isnan(m2o[:, 0])):
                ax.plot(m2o[:, 0], m2o[:, 1], color=C_OPT, alpha=0.95, linewidth=2.0, label="2D Opt (Mid)")
            ax.set_title("Wrist 2D Trajectory (Image, Proxy)", fontsize=ANALYSIS_SUBTITLE_FONTSIZE, fontweight='bold')
            ax.set_xlabel("u (px)")
            ax.set_ylabel("v (px)")
            ax.legend(loc="upper right", fontsize=9)

            # -------------------------
            # 19) Midpoint ↔ Wrist distance (raw/opt)
            # -------------------------
            ax = fig.add_subplot(gs[4, 2])
            ax.grid(True, alpha=0.35)
            ax.plot(frames, data["d_mid2w_raw"], color=C_RAW, alpha=ANALYSIS_ALPHA_RAW, linewidth=ANALYSIS_LINEWIDTH_AUX, label="Mid2Wrist Raw")
            ax.plot(frames, data["d_mid2w_opt"], color=C_OPT, alpha=ANALYSIS_ALPHA_OPT, linewidth=ANALYSIS_LINEWIDTH_MAIN, label="Mid2Wrist Opt")
            ax.set_title("Distance: Midpoint ↔ Wrist (Raw/Opt)", fontsize=ANALYSIS_SUBTITLE_FONTSIZE, fontweight='bold')
            ax.set_ylabel("m")
            ax.set_xlabel("Frame\nTime (s)")
            AriaHandsOps._set_frame_time_ticks(ax, frames, dt)
            ax.legend(loc="upper right", fontsize=9)

            # -------------------------
            # 20/21/22/23) Wrist/Midpoint linear & angular velocity (raw/opt) + limit line
            # -------------------------
            ax = fig.add_subplot(gs[4, 3])
            _plot_ts(ax, data["wrist_lin_raw"], data["wrist_lin_opt"],
                     ylabel="m/s", title="Wrist Linear Velocity |v| (Raw/Opt)",
                     label_raw="Wrist |v| Raw", label_opt="Wrist |v| Opt",
                     show_limit=cfg.OPT_V_LIMIT, limit_label=f"v_limit={cfg.OPT_V_LIMIT:.1f}m/s")

            ax = fig.add_subplot(gs[5, 0])
            _plot_ts(ax, data["wrist_ang_raw"], data["wrist_ang_opt"],
                     ylabel="rad/s", title="Wrist Angular Velocity |ω| (Raw/Opt)",
                     label_raw="Wrist |ω| Raw", label_opt="Wrist |ω| Opt",
                     show_limit=cfg.opt_w_limit, limit_label=f"ω_limit={cfg.opt_w_limit:.1f}rad/s")

            ax = fig.add_subplot(gs[5, 1])
            _plot_ts(ax, data["mid_lin_raw"], data["mid_lin_opt"],
                     ylabel="m/s", title="Midpoint Linear Velocity |v| (Raw/Opt)",
                     label_raw="Mid |v| Raw", label_opt="Mid |v| Opt",
                     show_limit=cfg.OPT_V_LIMIT, limit_label=f"v_limit={cfg.OPT_V_LIMIT:.1f}m/s")

            ax = fig.add_subplot(gs[5, 2])
            _plot_ts(ax, data["mid_ang_raw"], data["mid_ang_opt"],
                     ylabel="rad/s", title="Midpoint Angular Velocity |ω| (Raw/Opt)",
                     label_raw="Mid |ω| Raw", label_opt="Mid |ω| Opt",
                     show_limit=cfg.opt_w_limit, limit_label=f"ω_limit={cfg.opt_w_limit:.1f}rad/s")

            # -------------------------
            # Midpoint orientation axes (Raw/Opt): x-axis / y-axis / z-axis in world frame
            # -------------------------
            ax = fig.add_subplot(gs[6, 0])
            _plot_axis_vec(
                ax,
                data["mid_ax_raw"][:, 0, :],   # midpoint x-axis in world
                data["mid_ax_opt"][:, 0, :],
                title="Midpoint X-axis in World (Raw/Opt)"
            )

            ax = fig.add_subplot(gs[6, 1])
            _plot_axis_vec(
                ax,
                data["mid_ax_raw"][:, 1, :],   # midpoint y-axis in world
                data["mid_ax_opt"][:, 1, :],
                title="Midpoint Y-axis in World (Raw/Opt)"
            )

            ax = fig.add_subplot(gs[6, 2])
            _plot_axis_vec(
                ax,
                data["mid_ax_raw"][:, 2, :],   # midpoint z-axis in world
                data["mid_ax_opt"][:, 2, :],
                title="Midpoint Z-axis in World (Raw/Opt)"
            )

            # -------------------------
            # Text report panel: core statistics summary rendered as a monospace text box
            # -------------------------
            ax = fig.add_subplot(gs[6, 3])
            ax.axis("off")

            def count_grasps_from_seq(seq: np.ndarray) -> int:
                """Count grasp onset events (0→1 transitions) in a binary state sequence."""
                return int(np.sum((seq[1:] == 1) & (seq[:-1] == 0)))

            valid_frames = int(np.sum(data["conf"] > 0))
            grasps_cnt = count_grasps_from_seq(data["grasp"])

            # Velocity statistics: opt as primary metric
            peak_wrist_v = np.nanmax(data["wrist_lin_opt"]) if np.any(~np.isnan(data["wrist_lin_opt"])) else 0.0
            mean_wrist_v = np.nanmean(data["wrist_lin_opt"]) if np.any(~np.isnan(data["wrist_lin_opt"])) else 0.0
            peak_wrist_w = np.nanmax(data["wrist_ang_opt"]) if np.any(~np.isnan(data["wrist_ang_opt"])) else 0.0
            mean_wrist_w = np.nanmean(data["wrist_ang_opt"]) if np.any(~np.isnan(data["wrist_ang_opt"])) else 0.0

            peak_mid_v = np.nanmax(data["mid_lin_opt"]) if np.any(~np.isnan(data["mid_lin_opt"])) else 0.0
            mean_mid_v = np.nanmean(data["mid_lin_opt"]) if np.any(~np.isnan(data["mid_lin_opt"])) else 0.0
            peak_mid_w = np.nanmax(data["mid_ang_opt"]) if np.any(~np.isnan(data["mid_ang_opt"])) else 0.0
            mean_mid_w = np.nanmean(data["mid_ang_opt"]) if np.any(~np.isnan(data["mid_ang_opt"])) else 0.0

            # RMSE of position/rotation deviation between raw and optimized trajectories
            pos_rmse_mid = np.sqrt(np.nanmean(mid_pos_err**2)) if np.any(~np.isnan(mid_pos_err)) else 0.0
            rot_rmse_mid = np.sqrt(np.nanmean(mid_rot_err**2)) if np.any(~np.isnan(mid_rot_err)) else 0.0
            pos_rmse_wrist = np.sqrt(np.nanmean(wrist_pos_err**2)) if np.any(~np.isnan(wrist_pos_err)) else 0.0
            rot_rmse_wrist = np.sqrt(np.nanmean(wrist_rot_err**2)) if np.any(~np.isnan(wrist_rot_err)) else 0.0

            report = []
            report.append(f"ARIA HAND REPORT ({title_side})")
            report.append("-" * 34)
            report.append(f"Frames: {len(frames)}")
            report.append(f"Valid Frames: {valid_frames}")
            report.append(f"Grasp Events: {grasps_cnt}")
            report.append("")
            report.append("[OPT LIMITS]")
            report.append(f"v_limit: {cfg.OPT_V_LIMIT:.2f} m/s")
            report.append(f"w_limit: {cfg.opt_w_limit:.2f} rad/s")
            report.append("")
            report.append("[Wrist (Opt)]")
            report.append(f"Peak |v|: {peak_wrist_v:.3f} m/s")
            report.append(f"Mean |v|: {mean_wrist_v:.3f} m/s")
            report.append(f"Peak |ω|: {peak_wrist_w:.3f} rad/s")
            report.append(f"Mean |ω|: {mean_wrist_w:.3f} rad/s")
            report.append(f"RMSE Pos: {pos_rmse_wrist*100:.2f} cm")
            report.append(f"RMSE Rot: {rot_rmse_wrist:.2f} deg")
            report.append("")
            report.append("[Midpoint (Opt)]")
            report.append(f"Peak |v|: {peak_mid_v:.3f} m/s")
            report.append(f"Mean |v|: {mean_mid_v:.3f} m/s")
            report.append(f"Peak |ω|: {peak_mid_w:.3f} rad/s")
            report.append(f"Mean |ω|: {mean_mid_w:.3f} rad/s")
            report.append(f"RMSE Pos: {pos_rmse_mid*100:.2f} cm")
            report.append(f"RMSE Rot: {rot_rmse_mid:.2f} deg")

            ax.text(
                0.02, 0.98, "\n".join(report),
                va="top", ha="left",
                fontsize=10,
                family="monospace",
                bbox=dict(boxstyle="round,pad=0.5", fc="#111111", ec="#444444", alpha=0.95),
                color="white"
            )
            plt.subplots_adjust(left=0.05, right=0.95, top=0.92, bottom=0.05)
            try:
                plt.tight_layout(rect=[0, 0, 1, 0.965])
            except:
                pass
            plt.savefig(save_path, dpi=ANALYSIS_FIG_DPI)
            plt.close()
            print(f"[***] Hand analysis plot saved to: {save_path}")


    @staticmethod
    def print_summary_and_eval(aria_hands: AriaHands) -> None:
        """
        Print a formatted hand interaction and kinematics summary report to stdout.

        Reports: total frames, per-side hand presence count, grasp event counts,
        peak/mean wrist linear and angular velocity (from optimized trajectories),
        and an overall data quality rating based on hand presence coverage.

        Args:
            aria_hands (AriaHands): Full sequence hand tracking data.

        Returns:
            None. Outputs a bordered box report to stdout.
        """
        total_frames = len(aria_hands)
        r_frames = sum(1 for h in aria_hands.hands if h.hand_r)
        l_frames = sum(1 for h in aria_hands.hands if h.hand_l)

        lin_vels = []
        ang_vels = []
        for h_group in aria_hands.hands:
            for hand in [h_group.hand_r, h_group.hand_l]:
                if hand and hand.wrist_pose is not None:
                    lin_vels.append(np.linalg.norm(hand.wrist_lin_vel_opt_world))
                    ang_vels.append(np.linalg.norm(hand.wrist_ang_vel_opt_world))

        max_lin_v = max(lin_vels) if lin_vels else 0.0
        avg_lin_v = np.mean(lin_vels) if lin_vels else 0.0
        max_ang_v = max(ang_vels) if ang_vels else 0.0
        avg_ang_v = np.mean(ang_vels) if ang_vels else 0.0

        def count_grasps(hand_side: str) -> int:
            """Count grasp onset events (0→1 transitions) for one hand side."""
            states = [getattr(h, hand_side).grasp_state if getattr(h, hand_side) else 0 for h in aria_hands.hands]
            return sum(1 for i in range(1, len(states)) if states[i] == 1 and states[i-1] == 0)

        r_grasps = count_grasps('hand_r')
        l_grasps = count_grasps('hand_l')

        print("\n" + "╔" + "═" * 60 + "╗")
        print(f"║{'ARIA HAND INTERACTION & KINEMATICS REPORT':^60}║")
        print("╠" + "═" * 60 + "╣")
        print(f"║  - Total Frames       : {total_frames:<38} ║")
        print(f"║  - Hand Presence (R/L): {f'{r_frames} / {l_frames}':<38} ║")
        print(f"║  - Grasp Events (R/L) : {f'{r_grasps} / {l_grasps}':<38} ║")
        print(f"║ {'':<58} ║")
        print(f"║ [SMOOTHED KINEMATICS - OPTIMIZED] {'':<25} ║")
        print(f"║  - Peak Linear Speed  : {max_lin_v:>8.3f} m/s {'':<28} ║")
        print(f"║  - Mean Linear Speed  : {avg_lin_v:>8.3f} m/s {'':<28} ║")
        print(f"║  - Peak Angular Speed : {max_ang_v:>8.3f} rad/s {'':<26} ║")
        print(f"║  - Mean Angular Speed : {avg_ang_v:>8.3f} rad/s {'':<26} ║")

        # Quality score: average hand presence ratio across both hands
        quality_score = (r_frames + l_frames) / (2 * total_frames + 1e-6)
        quality = "EXCELLENT" if quality_score > 0.8 else "GOOD" if quality_score > 0.4 else "PARTIAL"
        print(f"║  - Overall Data Qual  : {quality:<38} ║")
        print("╚" + "═" * 60 + "╝\n")


    @staticmethod
    def _draw_skeleton(img: np.ndarray, hand: Any) -> np.ndarray:
        """
        Draw a 2D hand skeleton overlay on the image using Aria's official 21-keypoint layout.

        Uses mps.hand_tracking.kHandJointConnections for bone connectivity. Joint colors
        are per-finger and change between open-hand and grasp states. In grasp state,
        an extra outer glow ring is rendered on each joint for visual emphasis.

        Keypoint index convention (Aria MPS):
            0=ThumbCMC, 1=IndexMCP, 2=MiddleMCP, 3=RingMCP, 4=PinkyMCP,
            5=Wrist, 6-7=Thumb, 8-10=Index, 11-13=Middle, 14-16=Ring, 17-19=Pinky, 20=Palm.

        Args:
            img  (np.ndarray): BGR input image to draw on, shape (H, W, 3).
            hand (Any)       : AriaHandData object with:
                                 hand_keypoints_2d (np.ndarray, shape 21×2): 2D keypoints (px).
                                 grasp_state (int): 0=open, 1=closed/grasp.

        Returns:
            np.ndarray: Image with skeleton drawn in-place. Returned unchanged if
                        hand is None, keypoints are missing, or fewer than 21 points.
        """
        if hand is None or hand.hand_keypoints_2d is None:
            return img

        pts = hand.hand_keypoints_2d.astype(np.int32)
        is_grasp = (hand.grasp_state == 1)

        if len(pts) < 21: return img

        # Per-finger color mapping in BGR: [Thumb, Index, Middle, Ring, Pinky]
        if not is_grasp:
            # Pastel color scheme for open-hand state
            finger_colors = [
                (160, 160, 255), # Thumb  - Coral pink (reddish)
                (160, 255, 160), # Index  - Fresh green (greenish)
                (255, 210, 160), # Middle - Sky blue (bluish)
                (150, 250, 250), # Ring   - Bright yellow (yellowish)
                (250, 160, 250)  # Pinky  - Lavender purple (purplish)
            ]
        else:
            # Grasp state: every finger becomes pure red so the closed-hand
            # event is unambiguous at a glance.
            finger_colors = [(0, 0, 255)] * 5

        # Resolution-adaptive sizes (reference: 480-px-tall image).
        sc = img.shape[0] / 480.0
        bone_lw = max(1, int(round(1 * sc)))
        dot_r   = max(1, int(round(2 * sc)))
        glow_r  = max(2, int(round(3 * sc)))

        # Draw bone connections using official Aria joint topology (thin light gray)
        for conn in mps.hand_tracking.kHandJointConnections:
            idx1, idx2 = int(conn[0]), int(conn[1])
            p1, p2 = tuple(pts[idx1]), tuple(pts[idx2])
            if p1 != (0,0) and p2 != (0,0):
                cv2.line(img, p1, p2, (210, 210, 210), bone_lw, cv2.LINE_AA)

        # Map each keypoint index to its finger index for color lookup
        finger_map = {
            0:0, 6:0, 7:0,                # Thumb
            1:1, 8:1, 9:1, 10:1,          # Index
            2:2, 11:2, 12:2, 13:2,        # Middle
            3:3, 14:3, 15:3, 16:3,        # Ring
            4:4, 17:4, 18:4, 19:4         # Pinky
        }

        for i, pt in enumerate(pts):
            p = tuple(pt)
            if p == (0, 0): continue

            if is_grasp:
                # Grasp state: ALL 21 keypoints (including wrist/palm) are red.
                color = (0, 0, 255)
            else:
                # Open-hand state: keep per-finger pastels + special wrist/palm.
                if i == 5:
                    color = (255, 255, 255)
                elif i == 20:
                    color = (0, 0, 0)
                else:
                    f_idx = finger_map.get(i, 0)
                    color = finger_colors[f_idx]

            cv2.circle(img, p, dot_r, color, -1, cv2.LINE_AA)

            # Glow ring around joints in grasp state for visual emphasis
            if is_grasp:
                cv2.circle(img, p, glow_r, color, bone_lw, cv2.LINE_AA)

            # Thin gray outline on black/white wrist/palm in open-hand state only
            # (in grasp state they're already red — no outline needed).
            if not is_grasp and (i == 5 or i == 20):
                cv2.circle(img, p, dot_r, (150, 150, 150), bone_lw, cv2.LINE_AA)

        return img


    @staticmethod
    def _draw_axis(img: np.ndarray, pose: Optional[np.ndarray], k: np.ndarray, d: np.ndarray) -> np.ndarray:
        """
        Draw a stylized 3D coordinate axis gizmo (X/Y/Z arrows + base disk + laser pointer)
        projected onto the image at the location defined by the given pose.

        Gizmo elements:
          - Three arrowed axes: X=red, Y=green, Z=blue (OpenCV BGR convention).
          - A decorative base disk in the XZ plane for spatial grounding.
          - A laser pointer line extending along the X axis direction.
          - Semi-transparent blending (0.7 overlay + 0.3 original) for a clean look.

        Args:
            img  (np.ndarray)         : BGR input image, shape (H, W, 3).
            pose (np.ndarray or None) : 4×4 camera-space pose matrix (T_cam_hand).
                                        If None, the image is returned unchanged.
            k    (np.ndarray)         : Camera intrinsic matrix, shape (3, 3).
            d    (np.ndarray)         : Distortion coefficients, shape (4,) or (5,).

        Returns:
            np.ndarray: Image with the axis gizmo blended in.
                        Returns the original image if pose is None or origin is out of frame.
        """
        if pose is None: return img

        # 1. Extract rotation vector and translation vector
        r_vec, _ = cv2.Rodrigues(pose[:3, :3])
        t_vec = pose[:3, 3]

        # 2. Define points in 3D space
        axis_len_x = 0.06
        axis_len_y = 0.10
        axis_len_z = 0.06
        pointer_len = 0.10 # Pointer line length 12cm
        base_r = 0.025     # Base disk radius 2.5cm

        # Define: X, Y, Z axis endpoints, origin, pointer endpoint
        pts_3d = np.float32([
            [axis_len_x, 0, 0],          # X
            [0, axis_len_y, 0],          # Y (longer)
            [0, 0, axis_len_z],          # Z
            [0, 0, 0],                   # origin
            [pointer_len, 0, 0],         # pointer along X
        ])

        # Base disk: 16-point circle in the XZ plane
        num_circle_pts = 16
        circle_pts_3d = []
        for i in range(num_circle_pts):
            angle = 2 * np.pi * i / num_circle_pts
            # circle_pts_3d.append([base_r * np.cos(angle), base_r * np.sin(angle), 0]) # XY plane
            circle_pts_3d.append([base_r * np.cos(angle), 0, base_r * np.sin(angle)])# XZ plane
        pts_3d = np.append(pts_3d, np.float32(circle_pts_3d), axis=0)

        # 3. Project all 3D points to 2D pixel coordinates
        img_pts, _ = cv2.projectPoints(pts_3d, r_vec, t_vec, k, d)
        img_pts = [tuple(pt.ravel().astype(int)) for pt in img_pts]

        origin = img_pts[3]
        h, w = img.shape[:2]
        if not (0 <= origin[0] < w and 0 <= origin[1] < h):
            return img

        # --- Drawing start ---
        overlay = img.copy()

        # A. Draw base disk (semi-transparent ring in XZ plane)
        for i in range(num_circle_pts):
            p1 = img_pts[5 + i]
            p2 = img_pts[5 + (i + 1) % num_circle_pts]
            cv2.line(overlay, p1, p2, (200, 200, 200), 1, cv2.LINE_AA)

        # B. Draw laser pointer (long extension in X direction, cyan-yellow glow)
        laser_end = img_pts[4]
        cv2.line(overlay, origin, laser_end, (255, 255, 0), 1, cv2.LINE_AA)
        cv2.circle(overlay, laser_end, 2, (255, 255, 0), -1, cv2.LINE_AA)

        # C. Draw standard XYZ axes with arrows (BGR: X=red, Y=green, Z=blue)
        colors = [(0, 0, 255), (0, 255, 0), (255, 0, 0)]
        labels = ["X", "Y", "Z"]
        for i in range(3):
            cv2.arrowedLine(overlay, origin, img_pts[i], colors[i], 3, tipLength=0.3, line_type=cv2.LINE_AA)
            label_pos = (img_pts[i][0] + 8, img_pts[i][1] + 8)
            cv2.putText(overlay, labels[i], label_pos, cv2.FONT_HERSHEY_SIMPLEX,
                        0.6, colors[i], 2, cv2.LINE_AA)

        # D. Small white dot at the origin to mark the pivot point
        cv2.circle(overlay, origin, 3, (255, 255, 255), -1, cv2.LINE_AA)

        # Blend overlay with original for a semi-transparent effect
        return cv2.addWeighted(overlay, 0.7, img, 0.3, 0)


    @staticmethod
    def _draw_aria_hand_panel(
        img: np.ndarray,
        idx: int,
        hand: Any,
        is_right: bool,
        opt_v_limit: float,
    ) -> np.ndarray:
        """
        Draw a per-hand information panel (glass-style UI card) at the bottom corner of the image.

        The panel displays:
          - Hand side label and grasp state (OPEN / CLOSED), with a blinking red border on grasp.
          - Tracking confidence value.
          - Five per-finger flexion and abduction bars (normalized to [0, 1] range).
          - A wrist linear velocity gauge bar with current speed readout.

        Panel anchoring: right-hand → bottom-right corner; left-hand → bottom-left corner.
        All sizing is scaled proportionally to image width for resolution independence.

        Args:
            img      (np.ndarray): BGR image to draw on, shape (H, W, 3).
            idx      (int)       : Current frame index (used for blink animation timing).
            hand     (Any)       : AriaHandData object, or None if hand not detected.
            is_right (bool)      : True = right hand (bottom-right); False = left (bottom-left).
            opt_v_limit (float)

        Returns:
            np.ndarray: Image with the hand info panel drawn in-place.
        """
        is_blink = (idx // 5) % 2 == 0

        # Scale helpers: S() for pixel sizes, F() for font scale, T() for line thickness
        # Reference width 840 → sc=1.52 at 1280x960. Matches the SLAM panel's
        # layout reference so the bottom hand panels don't collide with the
        # top SLAM panels.
        img_h, img_w = img.shape[:2]
        sc = img_w / 840.0

        def S(val): return int(val * sc)
        def F(val): return max(0.3, val * sc)
        def T(val): return max(1, int(val * sc))

        w, h = S(200), S(180)
        margin = S(10)

        # Anchor position: right-hand panel at bottom-right, left-hand at bottom-left
        y = img_h - h - margin
        x = img_w - w - margin if is_right else margin

        # Joint angle key mapping: UI label → (flexion keys list, abduction key)
        mapping = {
            "Thu": (["Thumb_CMC_Flex", "Thumb_MCP_Flex", "Thumb_IP_Flex"], "Thumb_CMC_Abd"),
            "Ind": (["Index_MCP_Flex", "Index_PIP_Flex", "Index_DIP_Flex"], "Index_MCP_Abd"),
            "Mid": (["Middle_MCP_Flex", "Middle_PIP_Flex", "Middle_DIP_Flex"], "Middle_MCP_Abd"),
            "Rin": (["Ring_MCP_Flex", "Ring_PIP_Flex", "Ring_DIP_Flex"], "Ring_MCP_Abd"),
            "Pin": (["Pinky_MCP_Flex", "Pinky_PIP_Flex", "Pinky_DIP_Flex"], "Pinky_MCP_Abd")
        }

        # --- 2. State logic ---
        if hand is not None:
            is_grasp = (hand.grasp_state == 1)
            conf = hand.confidence
            state_str = "CLOSED" if is_grasp else "OPEN"
            col = (0, 0, 255) if is_grasp else (0, 191, 255)
            angle_data = hand.joint_angles.data if (hand.joint_angles and hand.joint_angles.data) else {}
        else:
            is_grasp = False; conf = 0.0; state_str = "N/A"
            col = (120, 120, 120); angle_data = {}

        # --- 3. Draw frosted glass background panel ---
        img = draw_glass_rect(img, (x, y), (x + w, y + h))
        if is_grasp and is_blink:
                cv2.rectangle(img, (x, y), (x + w, y + h), (0, 0, 255), T(2), cv2.LINE_AA)
                # Red dot at top-left corner as a grasp indicator
                cv2.circle(img, (x + S(15), y + S(18)), S(4), (0, 0, 255), -1, cv2.LINE_AA)

        # --- 4. Title row: centered hand side + grasp state label ---
        title = f"{'RIGHT' if is_right else 'LEFT'} HAND: {state_str}"
        font_scale = F(0.45)
        (t_w, _), _ = cv2.getTextSize(title, cv2.FONT_HERSHEY_DUPLEX, font_scale, T(1))
        t_x = x + (w - t_w) // 2
        cv2.putText(img, title, (t_x, y + S(25)), cv2.FONT_HERSHEY_DUPLEX, font_scale, col, T(1), cv2.LINE_AA)

        # --- 5. Confidence row ---
        conf_txt = f"CONFIDENCE: {conf:.2f}"
        # stat_txt = f"STATUS: {state_str}"
        cv2.putText(img, conf_txt, (x + S(10), y + S(45)), cv2.FONT_HERSHEY_DUPLEX, F(0.32), (200, 200, 200), T(1), cv2.LINE_AA)
        # cv2.putText(img, stat_txt, (x + S(105), y + S(45)), cv2.FONT_HERSHEY_DUPLEX, F(0.32), col, T(1), cv2.LINE_AA)

        # --- 6. Five-finger bars: top bar = flexion (norm. to 180°), bottom = abduction (norm. to 45°) ---
        finger_names = ["Thu", "Ind", "Mid", "Rin", "Pin"]
        max_bar_w = S(125)

        for i, ui_name in enumerate(finger_names):
            y_row = y + S(65 + i * 18)
            cv2.putText(img, ui_name, (x + S(10), y_row + S(8)), cv2.FONT_HERSHEY_DUPLEX, F(0.35), (255, 255, 255), T(1), cv2.LINE_AA)

            flex_keys, abd_key = mapping[ui_name]
            flex_sum = sum([angle_data.get(k, 0) for k in flex_keys])
            abd_val = angle_data.get(abd_key, 0)

            f_col = (0, 0, 255) if is_grasp else (200, 130, 60)
            f_w = int(min(flex_sum / 180.0, 1.0) * max_bar_w)
            a_w = int(min(abd_val / 45.0, 1.0) * max_bar_w)

            # Dark background slots for flexion (top) and abduction (bottom) bars
            cv2.rectangle(img, (x + S(55), y_row + S(1)), (x + S(55) + max_bar_w, y_row + S(4)), (50, 50, 50), -1)
            cv2.rectangle(img, (x + S(55), y_row + S(7)), (x + S(55) + max_bar_w, y_row + S(10)), (50, 50, 50), -1)

            if f_w > 0:
                cv2.rectangle(img, (x + S(55), y_row + S(1)), (x + S(55) + f_w, y_row + S(4)), f_col, -1, cv2.LINE_AA)
            if a_w > 0:
                cv2.rectangle(img, (x + S(55), y_row + S(7)), (x + S(55) + a_w, y_row + S(10)), (100, 200, 255), -1, cv2.LINE_AA)

        # --- 7. Velocity gauge: shows optimized wrist linear speed clamped to opt_v_limit ---
        if hand and hand.wrist_lin_vel_opt_world is not None:
            velocity_mag = np.linalg.norm(hand.wrist_lin_vel_opt_world)
        else:
            velocity_mag = 0.0

        v_y_row = y + S(158)
        cv2.putText(img, "VEL", (x + S(10), v_y_row + S(10)), cv2.FONT_HERSHEY_DUPLEX, F(0.35), (255, 255, 255), T(1), cv2.LINE_AA)

        max_vel_limit = opt_v_limit
        vel_ratio = min(velocity_mag / max_vel_limit, 1.0)
        vel_bar_w = int(vel_ratio * max_bar_w)

        # Dark gray background slot for velocity gauge
        cv2.rectangle(img, (x + S(55), v_y_row + S(2)), (x + S(55) + max_bar_w, v_y_row + S(10)), (40, 40, 40), -1)

        # Cyan below 1 m/s, yellow-green above (color shift signals high velocity)
        v_color = (255, 255, 0) if velocity_mag < 1.0 else (0, 255, 255)

        if vel_bar_w > 0:
            cv2.rectangle(img, (x + S(55), v_y_row + S(2)), (x + S(55) + vel_bar_w, v_y_row + S(10)), v_color, -1, cv2.LINE_AA)

        vel_text = f"{velocity_mag:.2f} m/s"
        cv2.putText(img, vel_text, (x + S(125), v_y_row - S(2)), cv2.FONT_HERSHEY_DUPLEX, F(0.3), v_color, T(1), cv2.LINE_AA)

        return img


    @staticmethod
    def _draw_opt_wrist_thumb_index_only(
        img: np.ndarray,
        aria_hand_data: Any,
        k: np.ndarray,
        d: np.ndarray,
        c2w: np.ndarray,
        draw_lines: bool = True,
        radius: int = 4,
        thickness: int = -1,
    ) -> np.ndarray:
        """
        Draw the 5 optimized key nodes and their skeletal connections, projected from
        world coordinates onto the camera image.

        Nodes drawn: wrist (W), thumb base, index base, thumb tip (T), index tip (I).
        Bone connectivity (when draw_lines=True):
            Wrist → Thumb Base → Thumb Tip
            Wrist → Index Base → Index Tip
        Fallback: if base knuckle coords are unavailable, connects Wrist → Tip directly.

        Node color coding (BGR):
            W (Wrist) = white | T (Thumb Tip) = red | I (Index Tip) = green | Base = cyan.

        Args:
            img           (np.ndarray): BGR image to draw on, shape (H, W, 3).
            aria_hand_data (Any)      : AriaHandData with optimized world-space fields:
                                          wrist_pose_opt_world, thumb/index_translation_opt_world,
                                          thumb/index_base_opt_world.
            k             (np.ndarray): Camera intrinsic matrix, shape (3, 3).
            d             (np.ndarray): Distortion coefficients.
            c2w           (np.ndarray): Camera-to-world 4×4 transform matrix.
            draw_lines    (bool)      : Whether to draw bone connection lines. Default True.
            radius        (int)       : Keypoint circle radius in pixels. Default 4.
            thickness     (int)       : Circle fill thickness (-1 = filled). Default -1.

        Returns:
            np.ndarray: Image with optimized keypoints and bones drawn in-place.
        """
        if aria_hand_data is None:
            return img

        T_w2c = np.linalg.inv(c2w)

        def _project_world_point(p_w: np.ndarray) -> Optional[Tuple[int, int]]:
            """Project a single world-space 3D point to image pixel coordinates (u, v)."""
            if p_w is None:
                return None
            p_w = np.asarray(p_w, dtype=np.float64).reshape(3)
            # Transform world → camera frame
            p_c = (T_w2c[:3, :3] @ p_w) + T_w2c[:3, 3]
            if p_c[2] <= 1e-6:  # Point is behind the camera
                return None
            rvec = np.zeros((3, 1), dtype=np.float64)
            tvec = np.zeros((3, 1), dtype=np.float64)
            uv, _ = cv2.projectPoints(p_c.reshape(1, 3), rvec, tvec, k, d)
            u, v = uv.reshape(2)
            h, w = img.shape[:2]
            if not (0 <= u < w and 0 <= v < h):
                return None
            return int(u), int(v)

        def _draw_one_hand(hand: Any) -> None:
            if hand is None:
                return

            # Fetch optimized world-space keypoint positions
            p_wrist_w = None
            if hand.wrist_pose_opt_world is not None:
                p_wrist_w = hand.wrist_pose_opt_world[:3, 3]

            p_t_tip_w = hand.thumb_translation_opt_world
            p_i_tip_w = hand.index_translation_opt_world

            # Base knuckle positions (may be absent in older data)
            p_t_base_w = getattr(hand, "thumb_base_opt_world", None)
            p_i_base_w = getattr(hand, "index_base_opt_world", None)

            # Project all key points to 2D pixel coordinates
            uv_wrist = _project_world_point(p_wrist_w)
            uv_t_tip = _project_world_point(p_t_tip_w)
            uv_i_tip = _project_world_point(p_i_tip_w)
            uv_t_base = _project_world_point(p_t_base_w)
            uv_i_base = _project_world_point(p_i_base_w)

            if uv_wrist is None and uv_t_tip is None and uv_i_tip is None:
                return

            C_WRIST = (255, 255, 255)  # White
            C_T_TIP = (0, 0, 255)      # Red
            C_I_TIP = (0, 255, 0)      # Green
            C_BASE  = (255, 255, 0)    # Cyan (for Knuckles)
            C_LINE  = (255, 255, 0)    # Cyan (for bones)

            if draw_lines:
                if uv_wrist and uv_t_base:
                    cv2.line(img, uv_wrist, uv_t_base, C_LINE, 1, cv2.LINE_AA)
                if uv_wrist and uv_i_base:
                    cv2.line(img, uv_wrist, uv_i_base, C_LINE, 1, cv2.LINE_AA)
                if uv_t_base and uv_t_tip:
                    cv2.line(img, uv_t_base, uv_t_tip, C_LINE, 1, cv2.LINE_AA)
                if uv_i_base and uv_i_tip:
                    cv2.line(img, uv_i_base, uv_i_tip, C_LINE, 1, cv2.LINE_AA)

                # Fallback: if Base not extracted (old data), connect Wrist -> Tip directly
                if uv_t_base is None and uv_wrist and uv_t_tip:
                    cv2.line(img, uv_wrist, uv_t_tip, C_LINE, 1, cv2.LINE_AA)
                if uv_i_base is None and uv_wrist and uv_i_tip:
                    cv2.line(img, uv_wrist, uv_i_tip, C_LINE, 1, cv2.LINE_AA)

            # Draw wrist node with outline and label
            if uv_wrist is not None:
                cv2.circle(img, uv_wrist, radius + 1, (0, 0, 0), 1, cv2.LINE_AA)
                cv2.circle(img, uv_wrist, radius, C_WRIST, thickness, cv2.LINE_AA)
                cv2.putText(img, "W", (uv_wrist[0] + 6, uv_wrist[1] - 6),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, C_WRIST, 1, cv2.LINE_AA)

            # Draw thumb knuckle base (cyan, with white core dot)
            if uv_t_base is not None:
                cv2.circle(img, uv_t_base, radius, C_BASE, thickness, cv2.LINE_AA)
                cv2.circle(img, uv_t_base, 2, (255, 255, 255), -1, cv2.LINE_AA)

            # Draw index knuckle base (cyan, with white core dot)
            if uv_i_base is not None:
                cv2.circle(img, uv_i_base, radius, C_BASE, thickness, cv2.LINE_AA)
                cv2.circle(img, uv_i_base, 2, (255, 255, 255), -1, cv2.LINE_AA)

            # Draw thumb tip (red, T label)
            if uv_t_tip is not None:
                cv2.circle(img, uv_t_tip, radius, C_T_TIP, thickness, cv2.LINE_AA)
                cv2.putText(img, "T", (uv_t_tip[0] + 6, uv_t_tip[1] - 6),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, C_T_TIP, 1, cv2.LINE_AA)

            # Draw index tip (green, I label)
            if uv_i_tip is not None:
                cv2.circle(img, uv_i_tip, radius, C_I_TIP, thickness, cv2.LINE_AA)
                cv2.putText(img, "I", (uv_i_tip[0] + 6, uv_i_tip[1] - 6),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, C_I_TIP, 1, cv2.LINE_AA)

        _draw_one_hand(aria_hand_data)

        return img


    @staticmethod
    def draw_aria_hands_panel(
        img: np.ndarray,
        idx: int,
        aria_hands_data: AriaHandsData,
        opt_v_limit: float,
    ) -> np.ndarray:
        """
        Draw UI info panels for both hands (right and left) on the image.

        Delegates to _draw_aria_hand_panel() for each side. The right-hand panel is
        placed at the bottom-right corner; the left-hand panel at the bottom-left.

        Args:
            img             (np.ndarray)   : BGR image to draw on, shape (H, W, 3).
            idx             (int)          : Current frame index (for blink animation).
            aria_hands_data (AriaHandsData): Container with hand_r and hand_l fields.
            opt_v_limit (float)

        Returns:
            np.ndarray: Image with both hand info panels drawn.
        """
        img = AriaHandsOps._draw_aria_hand_panel(img, idx, aria_hands_data.hand_r, True, opt_v_limit)
        img = AriaHandsOps._draw_aria_hand_panel(img, idx, aria_hands_data.hand_l, False, opt_v_limit)
        return img


    @staticmethod
    def _draw_advanced_hud(
        img: np.ndarray,
        hand: Any,
        k: np.ndarray,
        d: np.ndarray,
        c2w: np.ndarray,
        grasp_threshold: float,
    ) -> np.ndarray:
        """
        Draw an advanced HUD overlay showing pinch distance, arm length, and grasp state
        as annotated connection lines and floating label boxes.

        All displayed distances and connecting lines are computed exclusively from
        smoothed (Opt) world-space coordinates for temporal stability.

        Overlay elements:
          - Dashed line: thumb tip ↔ index tip (color changes with grasp state).
          - Solid line: midpoint → wrist.
          - Floating label near midpoint: "DIST(OPT): Xm" + grasp threshold.
          - Floating label near wrist: "ARM(OPT): Xm" (midpoint-to-wrist distance).
          - Leader lines connecting labels to their anchor points.

        Args:
            img  (np.ndarray): BGR image to draw on, shape (H, W, 3).
            hand (Any)       : AriaHandData with optimized world fields:
                                 wrist_pose_opt_world, thumb/index_translation_opt_world,
                                 midpoint_translation_opt_world, grasp_state.
            k    (np.ndarray): Camera intrinsic matrix, shape (3, 3).
            d    (np.ndarray): Distortion coefficients.
            c2w  (np.ndarray): Camera-to-world 4×4 transform matrix.
            grasp_threshold (float)

        Returns:
            np.ndarray: Image with HUD elements drawn in-place.
                        Returns the original image unchanged if hand is None,
                        wrist_pose_opt_world is None, or any key point is out of view.
        """
        def _project_world_to_2d(
            p_w: Optional[np.ndarray],
            c2w: np.ndarray,
            k: np.ndarray,
            d: np.ndarray
        ) -> Optional[np.ndarray]:
            """Project a world-space 3D point to 2D pixel coordinates as an int32 array."""
            if p_w is None: return None
            T_w2c = np.linalg.inv(c2w)
            p_c = (T_w2c[:3, :3] @ p_w) + T_w2c[:3, 3]
            if p_c[2] <= 1e-6: return None
            # rvec and tvec are zero because p_c is already in the camera frame
            uv, _ = cv2.projectPoints(p_c.reshape(1, 3), np.zeros(3), np.zeros(3), k, d)
            u, v = uv.reshape(2)
            return np.array([u, v], dtype=np.int32)

        def _draw_dotted_line(
            img: np.ndarray,
            p1: np.ndarray,
            p2: np.ndarray,
            color: Tuple[int, int, int],
            thickness: int = 1,
            gap: int = 4
        ) -> None:
            """Draw a dashed line between two 2D points by alternating drawn/skipped segments."""
            dist = np.linalg.norm(p1 - p2)
            if dist < 1e-3: return
            for i in range(0, int(dist), gap * 2):
                start = tuple((p1 + (p2 - p1) * (i / dist)).astype(np.int32))
                end = tuple((p1 + (p2 - p1) * ((i + gap) / dist)).astype(np.int32))
                cv2.line(img, start, end, color, thickness, cv2.LINE_AA)

        # 1. Safety check: ensure optimized data exists
        if hand is None or hand.wrist_pose_opt_world is None:
            return img

        # 2. Extract optimized world coordinates 3D points
        p_wrist_w = hand.wrist_pose_opt_world[:3, 3]
        p_thumb_w = hand.thumb_translation_opt_world
        p_index_w = hand.index_translation_opt_world
        p_mid_w   = hand.midpoint_translation_opt_world

        # 3. Compute optimized physical distances (for text display)
        grasp_dist_3d = np.linalg.norm(p_thumb_w - p_index_w)
        wrist_dist_3d = np.linalg.norm(p_mid_w - p_wrist_w)

        # 4. Project 3D points to 2D pixel coordinates
        uv_wrist = _project_world_to_2d(p_wrist_w, c2w, k, d)
        uv_thumb = _project_world_to_2d(p_thumb_w, c2w, k, d)
        uv_index = _project_world_to_2d(p_index_w, c2w, k, d)
        uv_mid   = _project_world_to_2d(p_mid_w, c2w, k, d)

        # If keypoints fail to project (e.g., out of view), skip HUD drawing
        if uv_wrist is None or uv_thumb is None or uv_index is None or uv_mid is None:
            return img

        # 5. UI color and style settings
        is_active = hand.grasp_state == 1
        COLOR_GRASP = (0, 215, 255) if not is_active else (0, 69, 255) # Gold vs orange-red
        COLOR_WRIST = (255, 255, 0)   # Cyan
        COLOR_TEXT  = (255, 255, 255) # White
        BG_COLOR    = (20, 20, 20)    # Dark background for label boxes

        # 6. Draw thumb-index dashed line and midpoint-wrist solid line
        _draw_dotted_line(img, uv_thumb, uv_index, COLOR_GRASP, 1, 4)
        cv2.line(img, tuple(uv_mid), tuple(uv_wrist), COLOR_WRIST, 1, cv2.LINE_AA)

        # 7. Determine label offset direction to avoid occluding the hand center
        h_img, w_img = img.shape[:2]
        offset_direction = -1 if uv_mid[0] > w_img // 2 else 1

        # --- Label 1: Grasp distance (pinch distance) --- [COMMENTED OUT — too visually busy]
        # tag1_pos = uv_mid + np.array([offset_direction * 70, -50])
        # cv2.line(img, tuple(uv_mid), tuple(tag1_pos), (150, 150, 150), 1, cv2.LINE_AA)
        #
        # txt_dist = f"DIST(OPT): {grasp_dist_3d:.3f}m"
        # txt_limit = f"THRS: {grasp_threshold:.3f}m"
        #
        # (tw1, th1), _ = cv2.getTextSize(txt_dist, cv2.FONT_HERSHEY_DUPLEX, 0.32, 1)
        # (tw2, th2), _ = cv2.getTextSize(txt_limit, cv2.FONT_HERSHEY_DUPLEX, 0.3, 1)
        # box_w = max(tw1, tw2) + 12
        # box_h = th1 + th2 + 15
        #
        # rect_start = (tag1_pos[0] - (box_w if offset_direction == -1 else 0), tag1_pos[1] - box_h)
        #
        # cv2.rectangle(img, rect_start, (rect_start[0] + box_w, rect_start[1] + box_h), BG_COLOR, -1)
        # if is_active:
        #     cv2.rectangle(img, rect_start, (rect_start[0] + box_w, rect_start[1] + box_h), COLOR_GRASP, 1, cv2.LINE_AA)
        #
        # cv2.putText(img, txt_dist, (rect_start[0] + 6, rect_start[1] + th1 + 5),
        #             cv2.FONT_HERSHEY_DUPLEX, 0.32, COLOR_TEXT, 1, cv2.LINE_AA)
        # cv2.putText(img, txt_limit, (rect_start[0] + 6, rect_start[1] + th1 + th2 + 10),
        #             cv2.FONT_HERSHEY_DUPLEX, 0.3, COLOR_GRASP, 1, cv2.LINE_AA)

        # --- Label 2: Midpoint-to-wrist arm length ---
        tag2_pos = uv_wrist + np.array([offset_direction * 50, 40])
        cv2.line(img, tuple(uv_wrist), tuple(tag2_pos), (150, 150, 150), 1, cv2.LINE_AA)

        txt_arm = f"ARM(OPT): {wrist_dist_3d:.3f}m"
        (tw3, th3), _ = cv2.getTextSize(txt_arm, cv2.FONT_HERSHEY_DUPLEX, 0.32, 1)
        rect_start2 = (tag2_pos[0] - (tw3 + 12 if offset_direction == -1 else 0), tag2_pos[1] - th3 - 8)

        cv2.rectangle(img, rect_start2, (rect_start2[0] + tw3 + 12, rect_start2[1] + th3 + 12), BG_COLOR, -1)
        cv2.putText(img, txt_arm, (rect_start2[0] + 6, rect_start2[1] + th3 + 6),
                    cv2.FONT_HERSHEY_DUPLEX, 0.32, COLOR_WRIST, 1, cv2.LINE_AA)

        return img


    @staticmethod
    def draw_aria_hands_skeleton(
        img: np.ndarray,
        aria_hands_data: AriaHandsData,
        k: np.ndarray,
        d: np.ndarray,
        c2w: np.ndarray,
        grasp_threshold: float,
        full_skeleton: bool = False,
    ) -> np.ndarray:
        """
        Full per-frame visualization entry point: renders the complete hand overlay for
        both hands including the advanced HUD, midpoint pose axis gizmo, and optimized keypoints.

        For each detected hand (right and/or left), applies in order:
          1. _draw_advanced_hud()               — pinch/arm distance labels and connecting lines.
          2. _draw_axis()                        — XYZ pose axis gizmo at the midpoint frame.
          3. _draw_opt_wrist_thumb_index_only()  — optimized wrist/thumb/index node overlay.

        Args:
            img             (np.ndarray)   : BGR image to draw on, shape (H, W, 3).
            aria_hands_data (AriaHandsData): Container with hand_r and hand_l fields.
            k               (np.ndarray)   : Camera intrinsic matrix, shape (3, 3).
            d               (np.ndarray)   : Distortion coefficients.
            c2w             (np.ndarray)   : Camera-to-world 4×4 transform matrix.
            grasp_threshold (float)

        Returns:
            np.ndarray: Image with all visualization layers rendered for both hands.
        """
        for hand in [aria_hands_data.hand_r, aria_hands_data.hand_l]:
            if hand is not None:
                img = AriaHandsOps._draw_advanced_hud(img, hand, k, d, c2w, grasp_threshold)
                img = AriaHandsOps._draw_axis(img, np.linalg.inv(c2w) @ hand.midpoint_pose_opt_world, k, d)
                if full_skeleton:
                    # Render the full 21-keypoint hand skeleton (all fingers + bones)
                    img = AriaHandsOps._draw_skeleton(img, hand)
                else:
                    # Render only the simplified parallel-jaw view (wrist + thumb + index)
                    img = AriaHandsOps._draw_opt_wrist_thumb_index_only(img, hand, k, d, c2w)
        return img
        